Try using an Enum instead of a boolean to pass down richer messages
+ `make test` fails with error message: "AttributeError: 'HeadStartEligibilityStatus' object has no attribute 'dtype'"